![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [20]:
my_array = np.arange(10)
print(my_array[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [21]:
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [22]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [23]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [24]:
my_mat = np.arange(1, 21)
my_mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
my_mat = my_mat.reshape(4,5)
my_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
my_mat = np.flip(my_mat)
my_mat

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [26]:
print(my_mat[::-1])

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [27]:
print(my_mat[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [34]:
print(my_mat[0:5:2, :6:2])

[[ 1  3  5]
 [11 13 15]]


In [230]:
my_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [35]:
print(my_mat[::1,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [40]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [41]:
lista_filtrada = []

for elem in x:
    if elem == "Loro":
        lista_filtrada.append(elem)

print(list(lista_filtrada))

[np.str_('Loro'), np.str_('Loro')]


In [42]:
loros = x[x == "Loro"]
loros

array(['Loro', 'Loro'], dtype='<U5')

In [44]:
indices_loros = np.where(x == "Loro")
loros = x[indices_loros]

print(loros)

['Loro' 'Loro']


In [46]:
loros = loros[loros == "Loro"]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [50]:
tw_matrix = np.arange(20)
tw_matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
x1,x2 = np.split(tw_matrix, 2)

In [52]:
x1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
x2.reshape(5,2)


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [57]:
array_0 = np.zeros(10)

In [58]:
array_0[3] = 1
array_0


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [242]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
print(array_0.nbytes)
print(array_0.dtype)

80
float64


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [243]:
exe_11 = np.arange(10, 50)
exe_11

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [244]:
exe_11[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [63]:
#exe_12 = [1,2,0,0,4,0]
#np.intersect1d(exe_12, exe_12) # No se quitar el 0

array([0, 1, 2, 4])

In [64]:
np.nonzero(exe_12)[0]


array([0, 1, 4])

In [65]:
np.argwhere(exe_12)

array([[0],
       [1],
       [4]])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [68]:
exe_13= np.random.randint(10, size = (1000,1000))
exe_13

array([[2, 6, 3, ..., 4, 1, 1],
       [2, 2, 2, ..., 9, 4, 2],
       [5, 6, 0, ..., 9, 1, 7],
       ...,
       [0, 0, 5, ..., 1, 7, 5],
       [9, 0, 2, ..., 1, 1, 7],
       [7, 9, 9, ..., 6, 5, 2]])

In [247]:
np.min(exe_13), np.max(exe_13)

(np.int64(0), np.int64(9))

In [69]:
print(exe_13.min(), exe_13.max(), exe_13.sum())

0 9 4500313


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [249]:
vector_aleatorio = np.random.rand(30)
vector_aleatorio

array([0.98470688, 0.58882179, 0.91834653, 0.3017686 , 0.698978  ,
       0.57562883, 0.55354737, 0.18740139, 0.36800929, 0.87365789,
       0.04875605, 0.74621032, 0.88449905, 0.99938611, 0.20824131,
       0.82477624, 0.96742747, 0.84939156, 0.27037027, 0.77862539,
       0.37412848, 0.58857436, 0.7498397 , 0.46195963, 0.94914373,
       0.29644312, 0.73470298, 0.91389285, 0.88352131, 0.55088064])

In [250]:
media = np.mean(vector_aleatorio)
media

np.float64(0.6377212379668952)

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [251]:
array = np.zeros((6, 6), dtype=int)
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [252]:
array[0, :] = 1  # Borde superior
array[-1, :] = 1  # Borde inferior
array[:, 0] = 1  # Borde izquierdo
array[:, -1] = 1 
array


array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [74]:
matriz = np.zeros((8, 8), dtype=int)

matriz[0::2, 1::2] = 1  # Rellena con 1s en las posiciones impares de las filas pares
matriz[1::2, ::2] = 1
matriz

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
np.tile(10)

## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [88]:
exe_17 = np.tile(exe_17, (4,4))
exe_17

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [81]:
M = np.random.random((5, 5))
M

array([[0.19021643, 0.34970478, 0.15238577, 0.96469509, 0.74407625],
       [0.52797512, 0.73473854, 0.27631864, 0.15355065, 0.64815687],
       [0.58907328, 0.44235318, 0.01735318, 0.21567904, 0.46774235],
       [0.77900526, 0.84765022, 0.826155  , 0.09438256, 0.64741606],
       [0.98699351, 0.6398298 , 0.55318471, 0.86495865, 0.79243601]])

In [82]:
media = np.mean(M)
media

np.float64(0.540241236953328)

In [84]:
desviacion_standar = np.std(M)
desviacion_standar

np.float64(0.28411243223105886)

In [86]:
(M - media) / desviacion_standar

array([[-1.231994  , -0.67063754, -1.36514783,  1.49396437,  0.71744488],
       [-0.04317348,  0.68457863, -0.92893717, -1.36104775,  0.37983426],
       [ 0.17187576, -0.34453986, -1.84042652, -1.1423724 , -0.25517677],
       [ 0.8403857 ,  1.08199765,  1.00634021, -1.56930365,  0.37722679],
       [ 1.57244887,  0.3505252 ,  0.04555758,  1.14291869,  0.88765836]])

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [261]:
exe_19 = np.arange(10)
exe_19

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [267]:
nuevo_array = exe_19.copy()
nuevo_array[(nuevo_array >= 3) & (nuevo_array <= 8)] = -1
nuevo_array

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9])

In [87]:
contador = 0
contador += 1
contador

1